rm images/airplane/*
rm images/automobile/*
rm images/bird/*
rm images/cat/*
rm images/deer/*
rm images/dog/*
rm images/frog/*
rm images/horse/*
rm images/ship/*
rm images/truck/*
python gen_img_list.py